# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 07:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_start_time', models.DateTimeField()),
                ('assigned_end_time', models.DateTimeField()),
                ('event_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'assignmentData',
            },
        ),
        migrations.CreateModel(
            name='AvailableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_start_time', models.DateTimeField()),
                ('available_end_time', models.DateTimeField()),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'availableData',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('user_email', models.EmailField(max_length=70, unique=True)),
                ('client_secret_file', django.contrib.postgres.fields.jsonb.JSONField()),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('personal_email', models.EmailField(max_length=70, unique=True)),
                ('Username', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AddField(
            model_name='availabledata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capi.UserData'),
        ),
        migrations.AddField(
            model_name='assignementdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capi.UserData'),
        ),
    ]
