# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='timeZone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
