# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-27 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Username',
            new_name='username',
        ),
    ]
