# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='name',
        ),
        migrations.AlterField(
            model_name='availabledata',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='client_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='client_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personal_email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
