# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0002_auto_20190722_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Credentials_db',
        ),
    ]
