# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0003_auto_20190722_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials_db',
            name='user_email',
            field=models.EmailField(default='gaurav.pg007@gmail.com', max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
