# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 06:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0004_credentials_db_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials_db',
            name='client_secret_file',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignementdata',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='capi.Userdata'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='userID',
            field=models.AutoField(db_column='userID', primary_key=True, serialize=False),
        ),
    ]
