# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0005_auto_20190723_0654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials_db',
            new_name='CredentialsDB',
        ),
    ]
