# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0007_auto_20190723_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsdb',
            name='user_email',
            field=models.EmailField(default='gaurav.chaturvedi@squadrun.co', max_length=70),
        ),
    ]
