# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0009_auto_20190723_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsdb',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='credentialsdb',
            name='client_secret',
        ),
    ]
