# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi', '0010_auto_20190723_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabledata',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='assignementdata',
            name='userID',
        ),
        migrations.AddField(
            model_name='assignementdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='capi.Userdata'),
            preserve_default=False,
        ),
    ]
